name: Build

on:
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [x86_64]
        mode: [release]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - name: Get current date as package key
      id: cache_key
      run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install clang build-essential

    # Build the serv
    - name: Build IRC
      run: make -j && make fclean && make -j DEBUG=true
